FROM golang:1.22.0-alpine3.19 AS Builder

RUN apk add git bash gcc musl-dev upx
RUN apk add tzdata

WORKDIR /app

ENV GO111MODULE=on
ENV CGO_ENABLED=0
ENV GOPROXY=https://goproxy.cn
COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .